// Generated by CoffeeScript 1.6.2
var isJSExtensionRe, isJSXExtensionRe, isJSXPragmaRe, react, through;

react = require('react-tools');

through = require('through');

isJSXExtensionRe = /^.+\.jsx$/;

isJSExtensionRe = /^.+\.js$/;

isJSXPragmaRe = /\/\*\* +@jsx +React.DOM +\*\//;

module.exports = function(file) {
  var compile, data, isJSXExtension, isJSXPragma, write;

  isJSXExtension = isJSXExtensionRe.exec(file);
  isJSXPragma = void 0;
  data = '';
  write = function(chunk) {
    var firstLine, newLineIdx;

    data += chunk;
    if (isJSXPragma === void 0) {
      newLineIdx = data.indexOf('\n');
      if (newLineIdx > -1) {
        firstLine = data.substr(0, newLineIdx).trim();
        return isJSXPragma = isJSXPragmaRe.exec(firstLine);
      }
    }
  };
  compile = function() {
    if (isJSXExtension || isJSXPragma && isJSExtensionRe.exec(file)) {
      if (isJSXExtension && !isJSXPragma) {
        data = '/** @jsx React.DOM */\n' + data;
      }
      this.queue(react.transform(data));
    } else {
      this.queue(data);
    }
    return this.queue(null);
  };
  return through(write, compile);
};
